version: '3'

services:

  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: elijah798/noaa-api-assessment-image:backend
    ports:
      - "4000:4000"
  frontend:
    build: 
      context: ./interface/
      dockerfile: Dockerfile
    image: elijah798/noaa-api-assessment-image:frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend